### ISSUE TITLE
Failed loading plugin

### ISSUE THREAD

**Issue by alexs404** [IllidanS4/PawnPlus#10]
Hey there. 
I want to start to use your plugin on my game server.  I have tried to use it with my Linux Server (CentOS 7.5.1804), but it fails to start. Error - `Failed (plugins/PawnPlus.so: undefined symbol: _ZN4impl11native_infoIXadL_ZN7Natives7var_subEP6tagAMXPiEEE4nameE)`.  How can you help us?

**Comment by alexs404** [comment]
I downloaded  the Linux release

**Comment by IllidanS4** [comment]
Looks like the Linux version had broken linking of natives. Please use v0.10.1.
