### ISSUE TITLE
a question about default callbacks

### ISSUE THREAD

**Issue by omcho420** [IllidanS4/PawnPlus#17]
Is it possible to "re-write" the default callbacks, so we can use dynamically sized strings in default callbacks

Example:
public OnPlayerText(playerid, text[])

I started using this plugin few hours ago and I'm a newbie in pawn so I would like to know if we can do this or is "text[]" already a dynamically sized string by default?

**Comment by omcho420** [comment]
I tried editing the a_samp file to "forward OnPlayerText(playerid, String:text[]);" it seems to work but I'm not sure that it's that easily editable, right?

**Comment by IllidanS4** [comment]
There is no need to. When a callback is executed, the necessary space for the string is always allocated so it fits. Use `str_new` to construct the dynamic string.

**Comment by omcho420** [comment]
Thanks for the information and sorry for opening an 'issue' for this
