### ISSUE TITLE
samp-server.exe is not shut down correctly

### ISSUE THREAD

**Issue by George480** [IllidanS4/PawnPlus#18]
```Pawn
#include <a_samp>
#include <PawnPlus>

main() {}
```

When typing `exit` on console or calling `SendRconCommand("exit");`, the result is:
![Untitled](https://user-images.githubusercontent.com/5148529/62869185-fdba6d80-bd1f-11e9-9a63-a2eac04066ad.png)

If I click on Debug, the result is:
```
The thread 0x... has exited with code 0 (0x0).
The thread 0x... has exited with code 3 (0x3).
The thread 0x... has exited with code 3 (0x3).
The program '[5928] samp-server.exe' has exited with code 3 (0x3).
```

I use Windows 7 Ultimate (SP1).

**Comment by IllidanS4** [comment]
Hello, I am aware of the issue, which probably comes from one of the C++ destructors for static objects, but I haven't yet debugged the issue, since the stack trace doesn't point to my code and the issue shouldn't affect normal functioning of the server.

**Comment by George480** [comment]
Re-ordering the plugins seems to fix it for now.

**Comment by n0dai** [comment]
I have the same problem. Do you plan to fix it?
