### ISSUE TITLE
Unable to create directory "D:\Program Files\..."

### ISSUE THREAD

**Issue by Zeex** [IllidanS4/PawnPlus#22]
Because Output Directory is set to:

```
D:\Program Files\Rockstar Games\GTA San Andreas\Samp server\0.3.7\plugins\
```

in Visual Studio project properties, someone who doesn't have that directory can't build the plugin successfully after cloning it.

**Comment by IllidanS4** [comment]
It's there on purpose for me to debug easily in Visual Studio. It isn't present on Release.

**Comment by Zeex** [comment]
OK, fair enough.
