### ISSUE TITLE
undefined symbol "await"

### ISSUE THREAD

**Issue by silaeviddqd** [IllidanS4/PawnPlus#23]
Hi.

I'm using sampctl and installed your plugin to use tasks! 

The problem is when I'm trying to build the project it fails with an error says:
`'(error) undefined symbol "await"'`

Any ideas why this might happen and how to fix it?

Thanks!

**Comment by IllidanS4** [comment]
Most likely you haven't defined the necessary macro to enable this piece of syntax. You can either define `PP_SYNTAX_AWAIT` to enable `await` or just `PP_SYNTAX` to enable all custom pieces of syntax.
```pawn
#define PP_SYNTAX
#include <PawnPlus>
```

**Comment by silaeviddqd** [comment]
@IllidanS4 

Wow! Quickest answer on Github in my life! Thanks a lot! Have a nice day! 

Resolved.
