### ISSUE TITLE
Including PawnPlus crashes Compiler

### ISSUE THREAD

**Issue by Cubiq14** [IllidanS4/PawnPlus#32]
Hi,
I just started using PawnPlus and tried including it in my script.
But pawncc.exe crashes everytime I try to compile the script, after including PawnPlus.inc
Also crashes when I include it in a new blank script.

I'm using Version 1.2.1 of PawnPlus.
PawnPlus.inc is located in my pawno/includes directory
My includes:
   ```
   #include <a_samp>
   #include <PawnPlus>
   ```
I probably did something wrong, it's been a while since I used Pawno, but I could not figure out why the compiler crashes.

**Comment by IllidanS4** [comment]
Hi, please use the latest compiler version available here: https://github.com/pawn-lang/compiler/releases/

**Comment by Cubiq14** [comment]
Thank you,
I didn't realise I was using an old Compiler Version.
Works fine now :)
