### ISSUE TITLE
map_clear_deep removes reference

### ISSUE THREAD

**Issue by drakeee** [IllidanS4/PawnPlus#34]
I don't know if it's intentional or not buf if you use map_clear_deep map becomes invalid. It seems that map_clear don't reproduce this error.

Code:
```pawn
new Map:test = map_new();
map_clear_deep(test);

for_map(i : test)
{
		
}
```

Message log:
`[PawnPlus] map_iter: map reference is invalid (value 0x629CD4)`

**Comment by IllidanS4** [comment]
Already fixed by 28e569dd86edb9d8b87a0e6ef91bceb50ea86548.
