### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by Dmitriy51** [IllidanS4/PawnPlus#35]
have a question is it possible with this plugin to detect these functions?
### {
	return sqrtf(f[0] * f[0] + f[1] * f[1] + f[2] * f[2]);

**Comment by IllidanS4** [comment]
What do you mean by "detect"?

**Comment by Dmitriy51** [comment]
I didn't ask the right question, SORRY, is it possible to access such a function with your plugin?

**Comment by IllidanS4** [comment]
Sure, you can use the [debug API](https://github.com/IllidanS4/PawnPlus/wiki/Debug-natives) to browse non-public functions. Use `debug_symbol` to find the function and `debug_symbol_call` to invoke it. The script must be compiled with debug info attached.

**Comment by Dmitriy51** [comment]
ok, thank you
