### ISSUE TITLE
Backward Compatibility

### ISSUE THREAD

**Issue by fl0w3rs** [IllidanS4/PawnPlus#39]
Is the plugin backward compatible? I'm having problems with https://github.com/AGraber/pawn-plus-mysql which has version 1.0.0-pre4 installed in pawn.json.

**Comment by IllidanS4** [comment]
All versions since 1.0.0 should be backwards compatible. What is the issue?

**Comment by fl0w3rs** [comment]
Now I have

`mysql_query(mysql_connection_id, sprintf("SELECT * FROM accounts WHERE name = '%s'", PlayerName(playerid)), true);`

Changing to

`await mysql_aquery_s(mysql_connection_id, str_format("SELECT * FROM accounts WHERE name = '%s'", PlayerName(playerid)));`

TogglePlayerSpectating stops working
After auth SpawnPlayer calls, but spectating is still enabled
If you put print in onplayerspawn after calling TogglePlayerSpectation, then everything is printed

```
public OnPlayerSpawn(playerid)
{
	TogglePlayerSpectating(playerid, 0);
	print("OnPlayerSpawn");

	SetPlayerSkin(playerid, player[playerid][player_skin]);
    SetPlayerPosEx(playerid, -2244.9309, -2187.7476, 36.7330);
    SetPlayerFacingAngle(playerid, 204.0);

	if(player[playerid][player_death]) {
		SetPlayerPosEx(playerid, player[playerid][player_deathpos][0], player[playerid][player_deathpos][1], player[playerid][player_deathpos][2]);
		SetPlayerVirtualWorld(playerid, player[playerid][player_deathvw]);
		SetPlayerInterior(playerid, player[playerid][player_deathint]);
		UseAnim(playerid,"PED","FLOOR_hit_f",4.1,0,1,1,1,0);
		player[playerid][player_death] = false;
	}
	return 1;
}
```
Idk how it works, but if you change mysql_aquery back to mysql_query, everything works (without removing the plugin)

**Comment by fl0w3rs** [comment]
I was wrong, this is not TogglePlayerSpectating. If you remove it, it still doesn't work. The player simply does not spawn.

**Comment by fl0w3rs** [comment]
My plugins:
`mysql.so sscanf.so pawncmd.so streamer.so timerfix.so PawnPlus.so`
Includes:
![image](https://user-images.githubusercontent.com/47712545/92333871-8295c900-f091-11ea-8a95-58e0a0da83dd.png)

**Comment by ADRFranklin** [comment]
This seems more like an issue with how you think you should use it, versus how you are actually using it. 

The plugin is backwards compatible, and does work as intended, I think we would require more examples of your usage with the full details and also a walk through of what you expect it to do. It's possible where in your code, or a library you are using that it is now acting differently due to a change it what it expects, versus what it has been given.

In order to validate these claims, it would be better if you could re-create the issue in a fresh gamemode with only the most minimal amount of code / includes needed to reproduce it.

Also crashdetect does work with sampvoice, you just need to make sure it's loaded first.

**Comment by fl0w3rs** [comment]
What I wrote above is my only use in gm.
There are no problems with obtaining data, just the character does not spawn.

Full code of public -> https://hastebin.com/ezosanipex.cs
Then calls login dialog -> https://hastebin.com/ecuwotuyis.cpp
UploadPlayerAccount -> https://hastebin.com/xezapanure.cpp (works correctly too, sends welcome message and calls UploadAdminAccount, but SpawnPlayer does not work, OnPlayerSpawn is not called)

**Comment by fl0w3rs** [comment]
> This seems more like an issue with how you think you should use it, versus how you are actually using it.
> 
> The plugin is backwards compatible, and does work as intended, I think we would require more examples of your usage with the full details and also a walk through of what you expect it to do. It's possible where in your code, or a library you are using that it is now acting differently due to a change it what it expects, versus what it has been given.
> 
> In order to validate these claims, it would be better if you could re-create the issue in a fresh gamemode with only the most minimal amount of code / includes needed to reproduce it.
> 
> Also crashdetect does work with sampvoice, you just need to make sure it's loaded first.

By the way, thank you, I fixed crashdetect, but in the end it does not output anything related to my problem.

**Comment by fl0w3rs** [comment]
[server_log.txt](https://github.com/IllidanS4/PawnPlus/files/5183444/server_log.txt)

**Comment by ADRFranklin** [comment]
@fl0w3rs just before you use await, add this above it `task_yield(1);`. This should be all you need to do know for it to work.

**Comment by fl0w3rs** [comment]
Now it works. Thank you

**Comment by fl0w3rs** [comment]
I have one another question. Should I use task_yield(1) and await if I don't need to obtain data?
