### ISSUE TITLE
How did you create a custom locale?

### ISSUE THREAD

**Issue by aaangeletakis** [IllidanS4/PawnPlus#45]
Hello, I've been told that you've created a custom locale.

I have been sent here from [Stackoverflow: basic_regex throws bad_cast with char32_t](https://stackoverflow.com/questions/39126756/basic-regex-throws-bad-cast-with-char32-t/55323606?noredirect=1#comment117428901_55323606)

My goal is:

1. Using `std::basic_string<uint16_t>`
2. Use `std::regex` to find flags with `<Pattern>`
3. In order to avoid writing a parser and reduce maintenance.

Methods of implementation:
 - create a custom locale in order to achieve this
 - use `std::wregex` instead
     - Messy & not straightforward, thus should not be considered the solution

I have been looking through your code and this is what I've gathered of what you are doing:

1. `typedef cell char_type`
    - Defined as either const uchar or uchar in strings.cpp
2. In namespace std 
    - define 
        - a hash method for some reason
        - iterators
        - a ctype of \<cell\> that inherits from locale::facet
            - In order to use `uint16_t` would I need to replace anything that says [unsigned char with uint16_t?](https://github.com/IllidanS4/PawnPlus/blob/4038e8e0ae4d3a6dcd376f91466527cbee8065b7/plugins/src/modules/strings.h#L384)

I do not understand how to change this as there are no comments.

How can I use `uint16_t` instead of `typedef cell`?

**Comment by IllidanS4** [comment]
Hi; sorry for the lack of comments. It might not be straightforward, but it is fairly simple. Also not all things in strings.h/cpp, iterators and hashes for example. Start at `ctype` and `set_locale` (check its usage in main.cpp#Load) and start copying over all the components those things need. Simply change `cell` to `uint16_t`.

**Comment by IllidanS4** [comment]
Closed due to no further input.
