### ISSUE TITLE
PawnPlus crash

### ISSUE THREAD

**Issue by BronzeCheese** [IllidanS4/PawnPlus#7]
Hey there. I've just began using PawnPlus and tried to add it into my script, but now the server crashes whenever I log in.

Here is all the info

server-log https://pastebin.com/PG2BQ4DU
crashinfo https://pastebin.com/Q2P0bqbv
my implementation https://pastebin.com/fHexCzV7

Don't think it's something on my side as crashdetect doesn't seem to provide any useful information, hopefully you can fix this, or if I messed up please tell me, lol.

**Comment by IllidanS4** [comment]
Hi, thanks for reporting the crash! Based on a quick inspection, it seems the crash happens in a call to `amx_GetPublic`. Your code seems fine, so it might be a bug on my side or an incompatibility. Can you please attach mysql.dll, so I can see from where the call originated?

**Comment by BronzeCheese** [comment]
Oh dang, the mistake was actually on my side, didn't realize MySQL had printed an error in the log, and even more didn't expect it would crash the server. It's fixed now, sorry for bothering you! Keep up the great work!

**Comment by IllidanS4** [comment]
Glad to hear; if you find some other issue in the future, feel free to report. ;-)
